### ISSUE TITLE
Compatibility (More Shield Variants)

### ISSUE THREAD

**Issue by heromedel** [Ceedrich/bannerRetrieval#10]
Using this mod along side the More Shield Variants mod, the spruce (vanilla) shield still works as intended (banner is retrievable) the new modded shields do not have this feature. It would be really cool if you could make this mode compatible with it.

**Comment by Ceedrich** [comment]
Thanks for the suggestion. I added compatibility in the newest version.

**Comment by heromedel** [comment]
Oh awesome, Imma have to check this out, I hope it still works with 1.21.3
